# -*- coding: utf-8 -*-
"""Copy of netflix_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yuawyk5oIwoEq_GonnAYUqDf3t1MHu_s
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("netflix_titles.csv")
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year

# Summary
print("Total rows:", len(df))
print("Columns:", df.columns.tolist())
df.head()

sns.countplot(data=df, x='type', palette='Set2')
plt.title("Movies vs TV Shows")
plt.show()

df['year_added'].value_counts().sort_index().plot(kind='bar', color='skyblue')
plt.title("Titles Added Over the Years")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.show()

genres = df['listed_in'].str.split(', ').explode().value_counts().head(10)
genres.plot(kind='barh', color='purple')
plt.title("Top 10 Genres")
plt.xlabel("Number of Titles")
plt.gca().invert_yaxis()
plt.show()

df_movies = df[df['type'] == 'Movie'].copy()
df_movies['duration_mins'] = df_movies['duration'].str.extract('(\d+)').astype(float)
sns.histplot(df_movies['duration_mins'].dropna(), bins=20, color='green')
plt.title("Distribution of Movie Durations")
plt.xlabel("Minutes")
plt.show()